// creating a pipelone for jenkins
pipeline {
    agent 
        {
            node {
                label 'catalogue-nodejs'
            }
        }
    parameters {
        string(name: 'ENVIRONMENT', defaultValue: 'dev', description: 'Environment to deploy to')
        choice(name: 'deploy', description: 'Deploy to production', choices: ['dev', 'staging', 'prod'])

        }
    environment {
        course = 'jenkins'
        Appversion = ' '
        }
    // options {
    //     timeout(time: 20, unit: 'seconds')
    //     }    
        
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                sleep 5
            }
        }

        stage('Test') {
            steps {
                script {
                    sh """
                    echo 'environment is ${params.ENVIRONMENT}'

                    """
                }
                echo 'Testing...'
                echo 'testing github webhooks rsolved added 1'
            }
        }

        stage('Deploy') {
            when {
                    expression { return params.deploy == 'prod' }
                }
            steps {
                 echo "since the choice in parameters is: ${params.deploy} Deploying..."
            }
        }
        stage('reading jsonfile') {
            steps {
                script {
                    def packagejson= readJSON file: 'package.json'
                    appversion = packagejson.version
                    echo "App version is ${appversion}"
                }
            }
        }
    }
     post {
            always {
                echo 'This will always run'
                cleanWs()
            }
            success {
                echo 'This will run only if successful'
            }
            failure {
                echo 'This will run only if failed'
            }
            aborted {
                echo 'This will run only if aborted'
            }
        }

}